package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"maps"
	"net/http"
	"net/url"
	"os"
	"regexp"
	"slices"
	"strings"
)

var runtimeSourcePaths = []string{
	"src/Runner.Worker/ActionManifestManager.cs",
	"src/Runner.Worker/ActionManifestManagerLegacy.cs",
	"src/Misc/externals.sh",
	"src/Runner.Common/Constants.cs",
}

var acceptedRuntimePattern = regexp.MustCompile(`string\.Equals\(usingToken\.Value,\s*"(node[0-9]+)",\s*StringComparison\.OrdinalIgnoreCase\)`)
var bundledRuntimePattern = regexp.MustCompile(`(?m)^NODE([0-9]+)_VERSION="[0-9]+\.[0-9]+\.[0-9]+"\s*$`)
var migrationConstantPattern = regexp.MustCompile(`public static readonly string Node([0-9]+)(DeprecationUrl|RemovalDate)\s*=\s*"([^"\r\n]+)";`)
var migrationDeclarationPattern = regexp.MustCompile(`Node[0-9]+(?:DeprecationUrl|RemovalDate)\s*=`)

type runtimeInfo struct {
	Removed, Deprecated bool
	URL, RemovalDate    string
}

func runtimeNames(source []byte) []string {
	matches := acceptedRuntimePattern.FindAllSubmatch(source, -1)
	names := make([]string, 0, len(matches))
	for _, match := range matches {
		names = append(names, string(match[1]))
	}
	slices.Sort(names)
	return slices.Compact(names)
}

func collectRuntimes(sources map[string][]byte) (map[string]runtimeInfo, error) {
	names := runtimeNames(sources[runtimeSourcePaths[0]])
	if len(names) == 0 || !slices.Equal(names, runtimeNames(sources[runtimeSourcePaths[1]])) {
		return nil, errors.New("runner manifest parsers have no matching JavaScript runtime lists; review upstream source changes")
	}
	bundled := map[string]bool{}
	for _, match := range bundledRuntimePattern.FindAllSubmatch(sources[runtimeSourcePaths[2]], -1) {
		bundled["node"+string(match[1])] = true
	}
	if len(bundled) == 0 {
		return nil, errors.New("runner packaging source contains no recognized Node version declarations")
	}
	out := map[string]runtimeInfo{}
	for _, name := range names {
		out[name] = runtimeInfo{Removed: !bundled[name]}
	}
	for name := range bundled {
		if _, ok := out[name]; !ok {
			return nil, fmt.Errorf("bundled runtime %s is missing from the manifest parsers", name)
		}
	}
	migrations := migrationConstantPattern.FindAllSubmatch(sources[runtimeSourcePaths[3]], -1)
	if len(migrations) != len(migrationDeclarationPattern.FindAll(sources[runtimeSourcePaths[3]], -1)) {
		return nil, errors.New("unrecognized runtime migration declaration; review upstream source changes")
	}
	for _, match := range migrations {
		name, kind, value := "node"+string(match[1]), string(match[2]), string(match[3])
		info, ok := out[name]
		if !ok {
			continue // Migration constants can outlive a removed metadata value.
		}
		if kind == "DeprecationUrl" {
			u, err := url.Parse(value)
			if err != nil || u.Scheme != "https" || u.Host != "github.blog" || !strings.HasPrefix(u.Path, "/changelog/") {
				return nil, fmt.Errorf("unexpected deprecation URL for %s: %q", name, value)
			}
			info.Deprecated, info.URL = true, value
		} else {
			info.RemovalDate = value
		}
		out[name] = info
	}
	if !bytes.Contains(sources[runtimeSourcePaths[3]], []byte("class NodeMigration")) {
		return nil, errors.New("runner migration constants changed shape; review runtime lifecycle extraction")
	}
	for name, info := range out {
		if info.RemovalDate != "" && !info.Deprecated {
			return nil, fmt.Errorf("runtime %s has a removal date without deprecation evidence", name)
		}
	}
	return out, nil
}

func generateRuntimes(sources map[string][]byte, revision string) ([]byte, error) {
	if !revisionPattern.MatchString(revision) {
		return nil, errors.New("invalid runner runtime revision")
	}
	runtimes, err := collectRuntimes(sources)
	if err != nil {
		return nil, err
	}
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by actionlint/scripts/generate-action-metadata -runtimes. DO NOT EDIT.")
	fmt.Fprintf(&out, "// Sources: https://github.com/%s/tree/%s\n", repository, revision)
	fmt.Fprintln(&out, "\npackage actionlint\n\n// ActionRuntimes records accepted metadata values and the lifecycle of their bundled executables.\nvar ActionRuntimes = map[string]ActionRuntime{")
	for _, name := range slices.Sorted(maps.Keys(runtimes)) {
		r := runtimes[name]
		fmt.Fprintf(&out, "%q: {Removed: %t, Deprecated: %t, DeprecationURL: %q, RemovalDate: %q},\n", name, r.Removed, r.Deprecated, r.URL, r.RemovalDate)
	}
	fmt.Fprintln(&out, "}")
	return format.Source(out.Bytes())
}

func refreshRuntimes(ctx context.Context, client *http.Client, token, output string) error {
	// A single revision keeps the parser, package manifest, and migration constants consistent.
	// Resolve the newest commit touching any input, so unrelated runner commits do not churn tables.
	type commit struct {
		SHA    string
		Commit struct{ Committer struct{ Date string } }
	}
	var latest commit
	for _, path := range runtimeSourcePaths {
		data, err := download(ctx, client, "https://api.github.com/repos/"+repository+"/commits?path="+path+"&per_page=1", token)
		if err != nil {
			return err
		}
		var commits []commit
		if err := json.Unmarshal(data, &commits); err != nil {
			return fmt.Errorf("read runner runtime revision: %w", err)
		}
		if len(commits) == 0 || !revisionPattern.MatchString(commits[0].SHA) || commits[0].Commit.Committer.Date == "" {
			return errors.New("GitHub returned no valid runner runtime revision")
		}
		if commits[0].Commit.Committer.Date > latest.Commit.Committer.Date {
			latest = commits[0]
		}
	}
	sources := map[string][]byte{}
	for _, path := range runtimeSourcePaths {
		data, err := download(ctx, client, fmt.Sprintf("https://cdn.jsdelivr.net/gh/%s@%s/%s", repository, latest.SHA, path), "")
		if err != nil {
			return err
		}
		sources[path] = data
	}
	generated, err := generateRuntimes(sources, latest.SHA)
	if err != nil {
		return err
	}
	return os.WriteFile(output, generated, 0o644)
}
