// Generate offline Ruff selector metadata from a pinned upstream release.
// Run from the repository root with go run ./scripts/generate-ruff-selectors.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"regexp"
	"slices"
	"time"
)

const release = "0.17.0"
const revision = "5b27c1ccfaa230fb195855f5cf3404a21e3379cd"
const upstream = "https://raw.githubusercontent.com/astral-sh/ruff/" + revision + "/"

var codePattern = regexp.MustCompile(`^[A-Z]+[0-9]*$`)
var redirectPattern = regexp.MustCompile(`\("([A-Z]+[0-9]*)", "([A-Z]+[0-9]*)"\)`)

func selectors(schema, redirects []byte) ([]string, error) {
	var document struct {
		Definitions map[string]struct {
			Enum []string `json:"enum"`
		} `json:"definitions"`
	}
	if err := json.Unmarshal(schema, &document); err != nil {
		return nil, err
	}
	available := map[string]bool{}
	for _, selector := range document.Definitions["RuleSelector"].Enum {
		// Human-readable names and categories require Ruff's preview mode.
		if codePattern.MatchString(selector) {
			available[selector] = true
		}
	}
	if !available["ALL"] || !available["F821"] {
		return nil, errors.New("upstream schema has no supported RuleSelector definition")
	}
	aliases := map[string]string{}
	for _, match := range redirectPattern.FindAllSubmatch(redirects, -1) {
		aliases[string(match[1])] = string(match[2])
	}
	if aliases["C9"] != "C90" {
		return nil, errors.New("upstream selector redirects were not recognized")
	}
	result := make([]string, 0, len(available)+len(aliases))
	for selector := range available {
		result = append(result, selector)
	}
	for alias, target := range aliases {
		// Removed and test-only targets are absent from the release schema.
		if available[target] && !available[alias] {
			result = append(result, alias)
		}
	}
	slices.Sort(result)
	return result, nil
}

func fetch(path string) ([]byte, error) {
	client := &http.Client{Timeout: 30 * time.Second}
	request, err := http.NewRequestWithContext(context.Background(), http.MethodGet, upstream+path, nil)
	if err != nil {
		return nil, err
	}
	response, err := client.Do(request)
	if err != nil {
		return nil, err
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("fetch %s: %s", path, response.Status)
	}
	return io.ReadAll(io.LimitReader(response.Body, 4<<20))
}

func run() error {
	schema, err := fetch("ruff.schema.json")
	if err != nil {
		return err
	}
	redirects, err := fetch("crates/ruff_linter/src/rule_redirects.rs")
	if err != nil {
		return err
	}
	values, err := selectors(schema, redirects)
	if err != nil {
		return err
	}
	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by scripts/generate-ruff-selectors; DO NOT EDIT.")
	fmt.Fprintf(&output, "// Ruff %s: https://github.com/astral-sh/ruff/tree/%s\n\n", release, revision)
	fmt.Fprintln(&output, "package ruff\n\nvar supportedRuleSelectors = []string{")
	for _, value := range values {
		fmt.Fprintf(&output, "%q,\n", value)
	}
	fmt.Fprintln(&output, "}")
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile("internal/ruff/selectors_generated.go", formatted, 0o644)
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
