#:schema https://mise.jdx.dev/schema/mise.json

[wrappers.actionlint]
command = "go"
args    = ["run", "./cmd/actionlint"]
env     = { GOFLAGS = "-buildvcs=true" }

[tools]
go                           = { prefix = "1.27" }
node                         = { prefix = "26" }
"golangci-lint"              = { prefix = "2", depends = ["go"] }
"github:kjanat/runner"       = { prefix = "0.27" }
"github:koalaman/shellcheck" = { prefix = "0.11" }
"github:tombi-toml/tombi"    = { prefix = "1.8" }
"github:biomejs/biome"       = { prefix = "2.5", version_prefix = "@biomejs/biome@" }
"github:jgm/pandoc"          = { prefix = "3" }
"github:rhysd/actionlint"    = { version = "latest", depends = ["shellcheck"] }
"github:kjanat/actionlint"   = { version = "latest", depends = ["shellcheck"] }

[tools."github:kjanat/dprint"]
version = "0.59.0-kjanat"
depends = ["tombi", "go"]

[tool_alias]
tombi      = "github:tombi-toml/tombi"
shellcheck = "github:koalaman/shellcheck"

[settings]
idiomatic_version_file_enable_tools = ["go", "node"]
minimum_release_age                 = "0s"

[env]
GOFLAGS = "-buildvcs=true"

[tasks]
[tasks.build]
alias       = "bin"
description = "Build actionlint binary"
run         = "go build -o actionlint ./cmd/actionlint"
outputs     = ["./actionlint", "./actionlint.exe"]
env         = { GOFLAGS = "-buildvcs=true" }

[tasks.format]
alias       = ["f", "fmt"]
description = "Format code"
run         = "dprint fmt"
tools       = { tombi = { prefix = "1.8" } }
