// Code generated by actionlint/scripts/generate-action-metadata. DO NOT EDIT.
// Source: https://github.com/actions/runner/blob/fee24199cba8acf6c25da3a061c986066f42327a/src/Runner.Worker/action_yaml.json

package actionlint

var actionMetadataAvailability = map[string]actionExpressionAvailability{
	"inputs.*.default": {
		contexts: []string{"github", "job", "matrix", "runner", "strategy"},
		functions: map[string]actionFunctionLimits{
			"hashfiles": {1, 255},
		},
	},
	"outputs.*.value": {
		contexts:  []string{"env", "github", "inputs", "job", "matrix", "runner", "steps", "strategy"},
		functions: map[string]actionFunctionLimits{},
	},
	"runs.args.*": {
		contexts:  []string{"inputs"},
		functions: map[string]actionFunctionLimits{},
	},
	"runs.env": {
		contexts:  []string{"inputs"},
		functions: map[string]actionFunctionLimits{},
	},
	"runs.env.*": {
		contexts:  []string{"inputs"},
		functions: map[string]actionFunctionLimits{},
	},
	"runs.steps.*.continue-on-error": {
		contexts: []string{"env", "github", "inputs", "job", "matrix", "runner", "steps", "strategy"},
		functions: map[string]actionFunctionLimits{
			"hashfiles": {1, 255},
		},
	},
	"runs.steps.*.env": {
		contexts: []string{"env", "github", "inputs", "job", "matrix", "runner", "steps", "strategy"},
		functions: map[string]actionFunctionLimits{
			"hashfiles": {1, 255},
		},
	},
	"runs.steps.*.env.*": {
		contexts: []string{"env", "github", "inputs", "job", "matrix", "runner", "steps", "strategy"},
		functions: map[string]actionFunctionLimits{
			"hashfiles": {1, 255},
		},
	},
	"runs.steps.*.if": {
		contexts: []string{"env", "github", "inputs", "job", "matrix", "runner", "steps", "strategy"},
		functions: map[string]actionFunctionLimits{
			"always":    {0, 0},
			"cancelled": {0, 0},
			"failure":   {0, 0},
			"hashfiles": {1, 255},
			"success":   {0, 0},
		},
	},
	"runs.steps.*.name": {
		contexts: []string{"env", "github", "inputs", "job", "matrix", "runner", "steps", "strategy"},
		functions: map[string]actionFunctionLimits{
			"hashfiles": {1, 255},
		},
	},
	"runs.steps.*.run": {
		contexts: []string{"env", "github", "inputs", "job", "matrix", "runner", "steps", "strategy"},
		functions: map[string]actionFunctionLimits{
			"hashfiles": {1, 255},
		},
	},
	"runs.steps.*.shell": {
		contexts: []string{"env", "github", "inputs", "job", "matrix", "runner", "steps", "strategy"},
		functions: map[string]actionFunctionLimits{
			"hashfiles": {1, 255},
		},
	},
	"runs.steps.*.with": {
		contexts: []string{"env", "github", "inputs", "job", "matrix", "runner", "steps", "strategy"},
		functions: map[string]actionFunctionLimits{
			"hashfiles": {1, 255},
		},
	},
	"runs.steps.*.with.*": {
		contexts: []string{"env", "github", "inputs", "job", "matrix", "runner", "steps", "strategy"},
		functions: map[string]actionFunctionLimits{
			"hashfiles": {1, 255},
		},
	},
	"runs.steps.*.working-directory": {
		contexts: []string{"env", "github", "inputs", "job", "matrix", "runner", "steps", "strategy"},
		functions: map[string]actionFunctionLimits{
			"hashfiles": {1, 255},
		},
	},
}
var actionMetadataKeys = map[string][]string{
	"run-step":  {"continue-on-error", "env", "id", "if", "name", "run", "shell", "working-directory"},
	"uses-step": {"continue-on-error", "env", "id", "if", "name", "uses", "with"},
}
var actionMetadataSpecialFunctions = []string{"always", "cancelled", "failure", "hashfiles", "success"}
