// Code generated by actionlint/scripts/generate-action-metadata -runtimes. DO NOT EDIT.
// Sources: https://github.com/actions/runner/tree/1e694679869f59d42ce965dbc9bd5a074fdc7e82

package actionlint

// ActionRuntimes records accepted metadata values and the lifecycle of their bundled executables.
var ActionRuntimes = map[string]ActionRuntime{
	"node12": {Removed: true, Deprecated: false, DeprecationURL: "", RemovalDate: ""},
	"node16": {Removed: true, Deprecated: false, DeprecationURL: "", RemovalDate: ""},
	"node20": {Removed: false, Deprecated: true, DeprecationURL: "https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/", RemovalDate: "September 23rd, 2026"},
	"node24": {Removed: false, Deprecated: false, DeprecationURL: "", RemovalDate: ""},
}
