name: Problem Matchers
on:
  push:
    branches: [main, master]
    tags-ignore: ["*"]
  pull_request:
  workflow_dispatch:

permissions: { contents: read }

jobs:
  matcher-test:
    name: Test generate-actionlint-matcher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with: { persist-credentials: false }
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with: { go-version-file: go.mod }
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with: { node-version-file: .node-version, package-manager-cache: false }
      - uses: kjanat/runner@master
      - name: Update test data
        run: run -s make:scripts/generate-actionlint-matcher/testdata/escape.txt make:scripts/generate-actionlint-matcher/testdata/no_escape.txt make:scripts/generate-actionlint-matcher/testdata/want.json
        env: { SKIP_GO_GENERATE: "true" }
      - name: Test actionlint-matcher.json
        run: run test:matcher
      - name: Ensure .github/actionlint-matcher.json is up-to-date
        run: |
          run make:.github/actionlint-matcher.json
          if git diff --quiet; then
            echo 'OK'
          else
            echo 'ERROR! .github/actionlint-matcher.json is outdated. Update it by "run make:.github/actionlint-matcher.json"' >&2
            set -x
            git diff
            exit 1
          fi
