name: Pages

on:
  push: { branches: [main] }
  workflow_dispatch: null

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with: { persist-credentials: false }
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with: { go-version-file: go.mod }
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: "lts/*"
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Build and test playground
        run: |
          npm ci
          make -C playground build test
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        env:
          BUNDLE_GEMFILE: man/Gemfile
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - name: Build command manual
        env:
          BUNDLE_GEMFILE: man/Gemfile
        run: |
          bundle exec ronn man/actionlint.1.ronn
          sed -i 's|</head>|<link rel="stylesheet" href="dark.css">\n</head>|' man/actionlint.1.html
      - name: Package playground
        run: |
          mkdir playground-dist
          cp playground/index.html playground/index.js playground/index.js.map playground/index.ts playground/main.wasm playground/style.css playground-dist/
          cp -R playground/lib playground-dist/lib
          cp playground/index.html playground-dist/404.html
          cp man/actionlint.1.html playground-dist/man.html
          cp man/actionlint.1.html playground-dist/usage.html
          cp man/dark.css playground-dist/dark.css
      - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with: { path: playground-dist }

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: { name: github-pages, url: "${{ steps.deployment.outputs.page_url }}" }
    steps: [{ name: Deploy to GitHub Pages, id: deployment, uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 }] # v5
