name: Pages

on:
  push: { branches: [main] }
  workflow_dispatch: null

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with: { persist-credentials: false }
      - uses: actions/setup-go@v7
        with: { go-version-file: go.mod }
      - uses: actions/setup-node@v7
        with:
          node-version: "lts/*"
          cache: npm
          cache-dependency-path: playground/package-lock.json
      - name: Build and test playground
        run: |
          npm ci --prefix playground
          make -C playground build test
      - name: Build command manual
        env:
          BUNDLE_GEMFILE: man/Gemfile
          BUNDLE_JOBS: "4"
          BUNDLE_PATH: ${{ runner.temp }}/bundle
          BUNDLE_RETRY: "3"
        run: |
          bundle install
          bundle exec ronn man/actionlint.1.ronn
      - name: Package playground
        run: |
          mkdir playground-dist
          cp playground/index.html playground/index.js playground/index.js.map playground/index.ts playground/main.wasm playground/style.css playground-dist/
          cp -R playground/lib playground-dist/lib
          cp playground/index.html playground-dist/404.html
          cp man/actionlint.1.html playground-dist/man.html
          cp man/actionlint.1.html playground-dist/usage.html
      - uses: actions/configure-pages@v6
      - uses: actions/upload-pages-artifact@v5
        with: { path: playground-dist }

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: { name: github-pages, url: "${{ steps.deployment.outputs.page_url }}" }
    steps: [{ name: Deploy to GitHub Pages, id: deployment, uses: actions/deploy-pages@v5 }]
